version: '3.3'


services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment: 
            - SECRET_KEY=vk01v8za2906etgp-gcb+4f_b6ho39#3*pr42d6(h*=19b41y&
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        volumes:
            - .:/code
        ports:
            - 1337:8000
        depends_on:
            - db
            - redis
    db:
        image: postgres:11
        volumes:
            -  postgres_data:/var/lib/postgresql/data/
    redis:
        image: redis:alpine
    celery:
        build: .
        command: celery -A project worker -l info
        volumes:
            - .:/code
        environment:
            - DEBUG=1
            - SECRET_KEY=vk01v8za2906etgp-gcb+4f_b6ho39#3*pr42d6(h*=19b41y&
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        depends_on:
            - redis
    celery-beat:
        build: .
        command: celery -A project beat -l info
        volumes:
            - .:/code
        environment:
            - DEBUG=1
            - SECRET_KEY=vk01v8za2906etgp-gcb+4f_b6ho39#3*pr42d6(h*=19b41y&
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        depends_on:
            - redis

volumes:
    postgres_data: